# Dataset
The telecom customer churn dataset comes from an Iranian telecom company, with each row representing a customer over a year period. Along with a churn label, there is information on the customers' activity, such as call failures and subscription length.

In [ ]:
# For Google Drive only
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import numpy as np

customer = pd.read_csv("/content/drive/MyDrive/Data Science Lecture Notes/Bagging/customer_churn.csv")
# Directly read the file when running in local machine
customer.head()

,Call Failure,Complaints,Subscription Length,Charge Amount,Seconds of Use,Frequency of use,Frequency of SMS,Distinct Called Numbers,Age Group,Tariff Plan,Status,Age,Customer Value,Churn
0,8,0,38,0,4370,71,5,17,3,1,1,30,197.640,0
1,0,0,39,0,318,5,7,4,2,1,2,25,46.035,0
2,10,0,37,0,2453,60,359,24,3,1,1,30,1536.520,0
3,10,0,38,0,4198,66,1,35,1,1,1,15,240.020,0
4,3,0,38,0,2393,58,2,33,1,1,1,15,145.805,0

In [ ]:
customer.Churn.value_counts()

Churn
0    2655
1     495
Name: count, dtype: int64

In [ ]:
X = customer.drop("Churn", axis=1) # Independent variables
y = customer.Churn # Dependent variable

# Training a machine learning model

In [ ]:
# Split into train and test
from sklearn.model_selection import train_test_split, cross_val_score
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

# Train a machine learning model
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('classifier', DecisionTreeClassifier(random_state=42))
])

pipeline.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('classifier', DecisionTreeClassifier(random_state=42))])

# Model Evaluation

In [ ]:
from sklearn.metrics import classification_report

# Make prediction on the testing data
y_pred = pipeline.predict(X_test)

# Classification Report
print(classification_report(y_pred, y_test))

              precision    recall  f1-score   support

           0       0.96      0.97      0.96       806
           1       0.79      0.77      0.78       139

    accuracy                           0.94       945
   macro avg       0.88      0.87      0.87       945
weighted avg       0.94      0.94      0.94       945

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.946031746031746

In [ ]:
# Evaluate the classifier using cross-validation
cv_scores = cross_val_score(pipeline, X, y, cv=5)

print(f"Cross-validation scores: {cv_scores}")
print(f"Mean CV accuracy: {np.mean(cv_scores):.2f}")

Cross-validation scores: [0.95079365 0.94126984 0.93492063 0.94285714 0.92222222]
Mean CV accuracy: 0.94

# Bagging

In [ ]:
from sklearn.ensemble import BaggingClassifier

# Create a bagging classifier with the best decision tree found by grid search
bagging_classifier = BaggingClassifier(estimator=pipeline, n_estimators=50, random_state=42)

# Train the bagging classifier on the training data
bagging_classifier.fit(X_train, y_train)

BaggingClassifier(estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                            ('classifier',
                                             DecisionTreeClassifier(random_state=42))]),
                  n_estimators=50, random_state=42)

# Evaluating Ensemble Model

In [ ]:
# Make prediction on the testing data
y_pred = bagging_classifier.predict(X_test)

# Classification Report
print(classification_report(y_pred, y_test))

              precision    recall  f1-score   support

           0       0.97      0.97      0.97       813
           1       0.80      0.82      0.81       132

    accuracy                           0.95       945
   macro avg       0.89      0.89      0.89       945
weighted avg       0.95      0.95      0.95       945

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.946031746031746

In [ ]:
# Evaluate the classifier using cross-validation
cv_scores = cross_val_score(bagging_classifier, X, y, cv=5)

print(f"Cross-validation scores: {cv_scores}")
print(f"Mean CV accuracy: {np.mean(cv_scores):.2f}")

Cross-validation scores: [0.95396825 0.95714286 0.94126984 0.96190476 0.95714286]
Mean CV accuracy: 0.95